# Generated by Django 3.1.3 on 2020-12-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
